### ISSUE TITLE
Вот тут если после -f не передать имя файла, будет выход за границы массива

### ISSUE THREAD

**Issue by kozlyakov-m** [AndreiSerov/SE-task1#1]
https://github.com/AndreiSerov/kafedra_goodline/blob/0d00b699029327c326e7713ee64698f854225581/src/level8.kt#L19

**Comment by AndreiSerov** [comment]
И что? Задание было отловить несуществующий файл, а не все ошибки!

**Comment by kozlyakov-m** [comment]
> И что? Задание было отловить несуществующий файл, а не все ошибки!

Справедливо

**Comment by ABashkirova** [comment]
> И что? Задание было отловить несуществующий файл, а не все ошибки!

Никакая программа не должна завершаться с выброшенным исключением. 
Варианты решения:
- Принять ситуацию как "-f" — слово 
- Выйти из программы с кодом -1

**Comment by AndreiSerov** [comment]
Fixed
