### ISSUE TITLE
Пропущены краевые случаи при разделении строки на слова.

### ISSUE THREAD

**Issue by xwillq** [AndreiSerov/SE-task1#2]
Если в строке будет несколько пробелов подряд, то split(" ") разделит на пустые строки.
https://github.com/AndreiSerov/kafedra_goodline/blob/0d00b699029327c326e7713ee64698f854225581/src/level6.kt#L6

![image](https://user-images.githubusercontent.com/38136135/75605735-eace8580-5b17-11ea-9da6-cedcf7e77551.png)

**Comment by AndreiSerov** [comment]
Это фича! Будет сразу видно все сепараторы еще и с переносом каретки будет также.
