### ISSUE TITLE
Пропущены краевые случаи при разделении файла на слова.

### ISSUE THREAD

**Issue by xwillq** [AndreiSerov/SE-task1#3]
Не обрабатывает возможные перенос строки, табуляцию и несколько пробелов подряд.
https://github.com/AndreiSerov/kafedra_goodline/blob/0d00b699029327c326e7713ee64698f854225581/src/level8.kt#L19-L21

**Comment by AndreiSerov** [comment]
Я протестил на многострочном тексте и все работает корректно! Значит тут фича под капотом

**Comment by xwillq** [comment]
Вот результаты моего теста:
![image](https://user-images.githubusercontent.com/38136135/75606116-3b47e200-5b1c-11ea-91f8-6d3bd514af5c.png)

Файл: [input.txt](https://github.com/AndreiSerov/kafedra_goodline/files/4270191/input.txt)

**Comment by AndreiSerov** [comment]
пофикшено =) 
Заменил` " "` на `"\\p{Punct}+".toRegex()`

**Comment by AndreiSerov** [comment]
Не пофикшено =((

**Comment by AndreiSerov** [comment]
> Вот результаты моего теста:
> ![image](https://user-images.githubusercontent.com/38136135/75606116-3b47e200-5b1c-11ea-91f8-6d3bd514af5c.png)
> 
> Файл: [input.txt](https://github.com/AndreiSerov/kafedra_goodline/files/4270191/input.txt)

Теперь точно пофикшено
