### ISSUE TITLE
Файл compile.sh опубликован без разрешения на запуск

### ISSUE THREAD

**Issue by ABashkirova** [AndreiSerov/SE-task1#5]
После git clone необходимо вручную менять файл на запускаемый. Кажется git плохо отслеживает такие изменения, но это возможно :)

**Comment by AndreiSerov** [comment]
> После git clone необходимо вручную менять файл на запускаемый. Кажется git плохо отслеживает такие изменения, но это возможно :)

Добро, спасибо за заметку. впервые сталкиваюсь с такой проблемой.
Т е нужно вручную писать `chmod +x` ??

**Comment by AndreiSerov** [comment]
Не знаю сработает, но прошу проверить =)

**Comment by ABashkirova** [comment]
`cd lib && bash compile.sh` работает 

в readme что-то незапускаемое описано, не скопируешь и не вставишь в терминал `bash [path/]compile.sh` 

а вот вот так все еще доступа нет
`cd lib && ./compile.sh `

**Comment by AndreiSerov** [comment]
`cd lib && bash compile.sh`, если так в ридми пихну, то приемлемо? 

просто я имел ввиду, что если вы находитесь в рут папке проекта, то пишите `bash lib/compile.sh`, если вне его, то прописывайте полный путь, если в папке либ, то только `bash compile.sh` 
Часто встречал в литературе квадратные скобки вокруг необязательных членов, поэтому решил, что если помещу ратн в них, то это можно зачесть

**Comment by AndreiSerov** [comment]
Пробовал всячески наделить его правами через `chmod`, но он ни в какую не хочет работать без указания интерпретатора =( Поэтому в любом случае нужно говорить ему либо `sh`, либо `bash`, либо любой другой интерпретатор оболочки.

**Comment by ABashkirova** [comment]
Проверила на своем — работает, права такие:
-rwxr-xr-x

**Comment by ABashkirova** [comment]
Попробуй это:

```
chmod +x lib/compile.sh
git status 
git add lib/compile.s
git commit & push
````
или это
`git update-index --chmod=+x`
