### ISSUE TITLE
Файл compile.sh не работает из корневой директории

### ISSUE THREAD

**Issue by ABashkirova** [AndreiSerov/SE-task1#6]
Сценарий
git clone ...
./compile.sh

Результат:
ls: ../src/*.kt: No such file or directory

Если не заморачиваться, то хотя бы прописать это в readme :)

**Comment by AndreiSerov** [comment]
> Сценарий
> git clone ...
> ./compile.sh
> 
> Результат:
> ls: ../src/*.kt: No such file or directory
> 
> Если не заморачиваться, то хотя бы прописать это в readme :)

Я как бы не в курсе как должно быть правильно, но из того, что я нагуглил: там человек компилил ЖАРы в директорию либ, поэтому там и находится баш-скрыпт

**Comment by AndreiSerov** [comment]
Указал в ридми=)
