### ISSUE TITLE
warning: destructured parameter 'value' is never used

### ISSUE THREAD

**Issue by ABashkirova** [AndreiSerov/SE-task1#8]
В файлах, начиная с пятого, встречаются такие конструкции:
`.sortedBy { (key, value) -> key }`
Здесь переменная `value` не была использована, тогда лучше так:
`.sortedBy { (key, _) -> key }`

**Comment by AndreiSerov** [comment]
Fixed
Tnx for nice idea. I use underscore for the same way in python but i totally didnt know that it works in every PL
